#!/bin/bash

# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

if [ -f  .git/config ]; then
  DIR=$(pwd)
else
  echo "not in git root folder, exiting.."
  exit 1
fi

do_narmstrong(){
  # DRM + AUDIO PATCHES
  rm $PATCHES/a-* 2&>/dev/null
  cd ~/linux.narmstrong
  rm *.patch 2&>/dev/null
  git checkout linux-5.0-le-amlogic-gx
  git fetch origin linux-5.0-le-amlogic-gx
  git reset --hard origin/linux-5.0-le-amlogic-gx
  git format-patch --start-number 0001 a3b22b9f11d9fbc48b0291ea92259a5a810e9438 # 5.0-rc7
  for filename in *.patch; do mv "$filename" "a-$filename"; done;
  mv *.patch $DIR/$PATCHES/
}

do_elyotna(){
  # V4L2 VDEC PATCHES
  rm $PATCHES/b-* 2&>/dev/null
  cd ~/linux.elyotna
  rm *.patch 2&>/dev/null
  git checkout 5.0/v4l2-m2m-pr
  git fetch origin 5.0/v4l2-m2m-pr
  git reset --hard origin/5.0/v4l2-m2m-pr
  git format-patch --start-number 0001 8834f5600cf3c8db365e18a3d5cac2c2780c81e5 # 5.0-rc5
  for filename in *.patch; do mv "$filename" "b-$filename"; done;
  mv *.patch $DIR/$PATCHES/
#  cd $DIR
#  git checkout projects/Amlogic/patches/linux/b-0005-arm64-dts-meson-add-vdec-entries.patch
}

do_kwiboo(){
  # DW-HDMI AUDIO PATCHES
  rm $PATCHES/c-* 2&>/dev/null
  cd ~/linux.kwiboo
  rm *.patch 2&>/dev/null
  git fetch origin allwinner-4.20-audio
  git checkout allwinner-4.20-audio
  git reset --hard origin/allwinner-4.20-audio
  git format-patch --start-number 0001 8fe28cb58bcb235034b64cbbb7550a8a43fd88be # 4.20.0
  for filename in *.patch; do mv "$filename" "c-$filename"; done;
  mv *.patch $DIR/$PATCHES/
}

do_erstrom(){
  # ATH10K-SDIO PATCHES
  rm $PATCHES/d-* 2&>/dev/null
  cd ~/linux.erstrom
  rm *.patch 2&>/dev/null
  git fetch origin master
  git checkout master
  git reset --hard origin/master
  git format-patch --start-number 0001 9050858c21d0ec828261dec467136f4555604c05 # 5.1-rc4
  for filename in *.patch; do mv "$filename" "d-$filename"; done;
  mv *.patch $DIR/$PATCHES/
}

do_amlgx(){
  # AMLGX KERNEL PATCHES
  rm $PATCHES/e-* 2&>/dev/null
  cd ~/linux.chewitt
  rm *.patch 2&>/dev/null
  git fetch origin linux-5.1-amlgx
  git checkout linux-5.1-amlgx
  git reset --hard origin/linux-5.1-amlgx
  git format-patch --start-number 0001 ebd66bd23893c7d96378ca04f8ec32958aa9fdb1 #5.1-rc1
  for filename in *.patch; do mv "$filename" "e-$filename"; done;
  mv *.patch $DIR/$PATCHES/
}

do_amlg12(){
  # AMLG12 KERNEL PATCHES
  rm $PATCHES/e-* 2&>/dev/null
  cd ~/linux.chewitt
  rm *.patch 2&>/dev/null
  git fetch origin linux-5.1-amlg12
  git checkout linux-5.1-amlg12
  git reset --hard origin/linux-5.1-amlg12
  git format-patch --start-number 0001 4d1e213094d23f307013042077f3cde7d3423ffc #5.1-rc1
  for filename in *.patch; do mv "$filename" "e-$filename"; done;
  mv *.patch $DIR/$PATCHES/
}

do_ffmpeg(){
  # FFMPEG STATEFUL HWACCELL
  rm project/Amlogic/patches/ffmpeg/ffmpeg-hwaccel-* 2&>/dev/null
  cd ~/ffmpeg.lrusak
  rm *.patch 2&>/dev/null
  git fetch origin v4l2-request-hwaccel
  git checkout v4l2-request-hwaccel
  git reset --hard origin/v4l2-request-hwaccel
  git format-patch --start-number 0001 21c13d04e624aabc1c78998f910782db673070e6 # 4.0.3-Leia-18.2
  for filename in *.patch; do mv "$filename" "ffmpeg-hwaccel-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/ffmpeg/
}

case $2 in
  amlg12)
    PATCHES="packages/linux/patches/amlogic-g12"
    ;;
  amlgx|*)
    PATCHES="packages/linux/patches/amlogic-amlgx"
    ;;
esac

case $1 in
  narmstrong)
    do_narmstrong
    ;;
  upstream)
    do_upstream
    ;;
  elyotna|ely)
    do_elyotna
    ;;
  kwiboo)
    do_kwiboo
    ;;
  erstrom|ath10k)
    do_erstrom
    ;;
  amlgx)
    do_amlgx
    ;;
  amlg12)
    do_amlg12
    ;;
  ffmpeg)
    do_ffmpeg
    ;;
  *)
    echo "error: nothing selected!"
    ;;
esac

cd $DIR

exit
