#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team LibreELEC (https://libreelec.tv)

if [ -f  .git/config ]; then
  DIR="/home/chewitt/build/LibreELEC.chewitt"
else
  echo "not in git root folder, exiting.."
  exit 1
fi

do_narmstrong(){
  rm projects/Amlogic/patches/linux/a* 2&>/dev/null

#  local SEQUENCE="aa"
#  rm projects/Amlogic/patches/linux/$SEQUENCE-* 2&>/dev/null
#  cd ~/linux.narmstrong
#  rm *.patch 2&>/dev/null
#  git checkout amlogic/v4.20/drm-primary-scaling
#  git fetch origin amlogic/v4.20/drm-primary-scaling
#  git reset --hard origin/amlogic/v4.20/drm-primary-scaling
#  git format-patch --start-number 0001 84df9525b0c27f3ebc2ebb1864fa62a97fdedb7d # 4.19.0
#  rm 0005*
#  rm 0006*
#  rm 0007*
#  rm 0008*
#  rm 0009*
#  for filename in *.patch; do mv "$filename" "$SEQUENCE-$filename"; done;
#  mv *.patch $DIR/projects/Amlogic/patches/linux/

  # HDMI-PATCHSET
  local SEQUENCE="a"
  rm projects/Amlogic/patches/linux/$SEQUENCE-* 2&>/dev/null
  cd ~/linux.narmstrong
  rm *.patch 2&>/dev/null
  git fetch origin amlogic/v4.19/vpu-patches
  git checkout amlogic/v4.19/vpu-patches
  git reset --hard origin/amlogic/v4.19/vpu-patches
  git format-patch --start-number 0001 84df9525b0c27f3ebc2ebb1864fa62a97fdedb7d # 4.19.0
  for filename in *.patch; do mv "$filename" "$SEQUENCE-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/

  # DRM OVERLAY
#  local SEQUENCE="aa"
#  rm projects/Amlogic/patches/linux/$SEQUENCE-* 2&>/dev/null
#  cd ~/linux.narmstrong
#  rm *.patch 2&>/dev/null
#  git checkout amlogic/v4.20/drm-primary-scaling
#  git fetch origin amlogic/v4.20/drm-primary-scaling
#  git reset --hard origin/amlogic/v4.20/drm-primary-scaling
#  git format-patch --start-number 0001 84df9525b0c27f3ebc2ebb1864fa62a97fdedb7d # 4.19.0
#  for filename in *.patch; do mv "$filename" "$SEQUENCE-$filename"; done;
#  mv *.patch $DIR/projects/Amlogic/patches/linux/

  # VPU-4K
#  local SEQUENCE="ab"
#  rm projects/Amlogic/patches/linux/$SEQUENCE-* 2&>/dev/null
#  cd ~/linux.narmstrong
#  rm *.patch 2&>/dev/null
#  git checkout amlogic/v4.19/vpu-4k
#  git fetch origin amlogic/v4.19/vpu-4k
#  git reset --hard origin/amlogic/v4.19/vpu-4k
#  git format-patch --start-number 0001 acb1872577b346bd15ab3a3f8dff780d6cca4b70 # 4.18-rc7
#  for filename in *.patch; do mv "$filename" "$SEQUENCE-$filename"; done;
#  mv *.patch $DIR/projects/Amlogic/patches/linux/

  # VPU-ALT-CLK
#  local SEQUENCE="ac"
#  rm projects/Amlogic/patches/linux/$SEQUENCE-* 2&>/dev/null
#  cd ~/linux.narmstrong
#  rm *.patch 2&>/dev/null
#  git checkout amlogic/v4.19/vpu-alt-clk
#  git fetch origin amlogic/v4.19/vpu-alt-clk
#  git reset --hard origin/amlogic/v4.19/vpu-alt-clk
#  git format-patch --start-number 0001 9b79b14f4082a111f7cd278c091c1295d15ce295 # 4.18-rc7
#  for filename in *.patch; do mv "$filename" "$SEQUENCE-$filename"; done;
#  mv *.patch $DIR/projects/Amlogic/patches/linux/

  # FIX-DRM
#  local SEQUENCE="ad"
#  rm projects/Amlogic/patches/linux/$SEQUENCE-* 2&>/dev/null
#  cd ~/linux.narmstrong
#  rm *.patch 2&>/dev/null
#  git checkout amlogic/v4.19/fix-drm-min-max
#  git fetch origin amlogic/v4.19/fix-drm-min-max
#  git reset --hard origin/amlogic/v4.19/fix-drm-min-max
#  git format-patch --start-number 0001 17b57b1883c1285f3d0dc2266e8f79286a7bef38 # 4.19-rc6
#  for filename in *.patch; do mv "$filename" "$SEQUENCE-$filename"; done;
#  rm ad-0001-drm-fix-use-after-free-read-in-drm_mode_create_lease.patch
#  rm ad-0002-drm-cma-helper-Fix-crash-in-fbdev-error-path.patch
#  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_upstream(){
  # LINUX PATCHES
  rm projects/Amlogic/patches/linux/b-* 2&>/dev/null
  cd ~/linux.narmstrong
  rm *.patch 2&>/dev/null
  git checkout linux-4.19-le-amlogic-gx
  git fetch origin linux-4.19-le-amlogic-gx
  git reset --hard origin/linux-4.19-le-amlogic-gx
  git format-patch --start-number 0001 6bf4ca7fbc85d80446ac01c0d1d77db4d91a6d84 #4.19-rc5
  #rm 0001*
  #rm 0003*
  for filename in *.patch; do mv "$filename" "b-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_elyotna(){
  # VDEC PATCHES
  rm projects/Amlogic/patches/linux/c-* 2&>/dev/null
  cd ~/linux.elyotna
  rm *.patch 2&>/dev/null
  git checkout 4.19/v4l2-m2m-pr
  git fetch origin 4.19/v4l2-m2m-pr
  git reset --hard origin/4.19/v4l2-m2m-pr
  git format-patch --start-number 0001 d860fe744349fd5746a23fe56c74d57948762a60 # 4.19.0 + canvas
  for filename in *.patch; do mv "$filename" "c-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
  cd $DIR
  git checkout projects/Amlogic/patches/linux/c-0005-arm64-dts-meson-add-vdec-entries.patch
}

do_kwiboo(){
  # HDMI AUDIO PATCHES
  rm projects/Amlogic/patches/linux/d-* 2&>/dev/null
  cd ~/linux.kwiboo
  rm *.patch 2&>/dev/null
  git checkout hdmi-audio-4.18
  git fetch origin hdmi-audio-4.18
  git reset --hard origin/hdmi-audio-4.18
  git format-patch --start-number 0001 1e4b044d22517cae7047c99038abb444423243ca #4.18-rc4
  rm 0001*
  for filename in *.patch; do mv "$filename" "d-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_erstrom(){
  # ath10k-sdio PATCHES
  rm projects/Amlogic/patches/linux/e-* 2&>/dev/null
  cd ~/linux.erstrom
  rm *.patch 2&>/dev/null
  git checkout master
  git fetch origin master
  git reset --hard origin/master
  git format-patch --start-number 0001 94f742967c57a997ab239846be5eb48f5b1458e3 #4.19.0
  for filename in *.patch; do mv "$filename" "e-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/
}

do_lima(){
  # LIMA DRIVER
  rm projects/Amlogic/patches/linux/f-* 2&>/dev/null
  cd ~/linux.lima
  rm *.patch 2&>/dev/null
  git checkout lima-4.19-rc4
  git fetch origin lima-4.19-rc4
  git reset --hard origin/lima-4.19-rc4
  git format-patch --start-number 0001 7876320f88802b22d4e2daf7eb027dd14175a0f8 #4.19-rc4
  for filename in *.patch; do mv "$filename" "f-$filename"; done;
  mv *.patch $DIR/projects/Amlogic/patches/linux/

  cd $DIR

  # LIMA MESA PATCHES
  rm packages/graphics/mesa/a-* 2&>/dev/null
  cd ~/mesa.lima
  rm *.patch 2&>/dev/null
  git checkout lima-18.2
  git fetch origin lima-18.2
  git reset --hard origin/lima-18.2
  git format-patch --start-number 0001 f34bddc325c414cb8ee21666bd307512577efdef #18.2.5
  for filename in *.patch; do mv "$filename" "a-$filename"; done;
  mv *.patch $DIR/packages/graphics/mesa/patches/
}

case $1 in
  narmstrong)
    do_narmstrong
    ;;
  upstream)
    do_upstream
    ;;
  elyotna|ely)
    do_elyotna
    ;;
  kwiboo)
    do_kwiboo
    ;;
  erstrom|ath10k)
    do_erstrom
    ;;
  lima)
    do_lima
    ;;


  all|*)
    do_narmstrong
    do_upstream
    do_elyotna
    do_kwiboo
    do_erstrom
esac

cd $DIR

exit
